name: tests

on:
  push:
  pull_request:

jobs:
  shell-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        shell: [bash, zsh, nu]
    steps:
      - uses: actions/checkout@v4
      - uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: stable
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y gnupg zsh
      - name: Setup Nushell
        if: matrix.shell == 'nu'
        uses: hustcer/setup-nu@v3
        with:
          check-latest: true
      - name: Run tests
        run: |
          if [ "${{ matrix.shell }}" = "bash" ]; then
            make test-bash
          elif [ "${{ matrix.shell }}" = "zsh" ]; then
            make test-zsh
          else
            make test-nu
          fi

  manager-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: stable
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y gnupg git
      - name: lazy.nvim compatibility
        run: make test-lazy
      - name: packer compatibility
        run: make test-packer
